configurations:
  content_keywords_list: ["Future KPIS", "KPIs Achieved", "Business Growth Strategies","Focus Area", "Current Achievements", "Financial Statement",  "Balance Sheet", "Income Statement", "Investments", "Future Plan", "Governance", "Risks", "Stakeholder Engagement", "Net Debt", "Technology Focus", "Future Technologies", "Partners", "Merger and Acquisitions", "Market Share", "Innovation", "Product Offering", "Products", "Customer Experience", "Sustainability" ]
  vector_database_config:
    collection_name: "business_report_analysis"
  embedding_model_config:
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    max_seq_length: 256
    chunk_size: 1000
    chunk_overlap: 0
  llm_model_config:
    groq_model:
      model_id: "qwen-2.5-32b"
      temperature: 0
    gemini_model:
      model_id: "gemini-2.0-flash"
      temperature: 0